{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "keel.fullname" . }}
  labels:
    {{- include "keel.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/instance
        operator: In
        values: [{{ .Release.Name }}]
      - key: app.kubernetes.io/name
        operator: In
        values: [{{ include "keel.name" . }}]
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
