// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: internal/connector/proto/forward.proto

package connector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ForwardRequest is the message sent to an OutputConnector.
// All fields are serializable — designed for future out-of-process plugin transport.
type ForwardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// topic is the Kafka topic to publish to.
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// payload is the raw message bytes (typically JSON).
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// headers are Kafka record headers (key-value pairs).
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// device_id is the device identifier (required by Ditto's hono-to-ditto mapping).
	DeviceId string `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// tenant_id is the tenant identifier (required by Ditto's hono-to-ditto mapping).
	TenantId      string `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_internal_connector_proto_forward_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_connector_proto_forward_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_internal_connector_proto_forward_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ForwardRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ForwardRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ForwardRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ForwardRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// ForwardResponse is the response from an OutputConnector.
type ForwardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates the message was forwarded successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// error contains an error message if success is false.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_internal_connector_proto_forward_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_connector_proto_forward_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_internal_connector_proto_forward_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_connector_proto_forward_proto protoreflect.FileDescriptor

const file_internal_connector_proto_forward_proto_rawDesc = "" +
	"\n" +
	"&internal/connector/proto/forward.proto\x12\tconnector\"\xf8\x01\n" +
	"\x0eForwardRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12@\n" +
	"\aheaders\x18\x03 \x03(\v2&.connector.ForwardRequest.HeadersEntryR\aheaders\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x0fForwardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB:Z8github.com/keel-iot/keel-mqtt-gateway/internal/connectorb\x06proto3"

var (
	file_internal_connector_proto_forward_proto_rawDescOnce sync.Once
	file_internal_connector_proto_forward_proto_rawDescData []byte
)

func file_internal_connector_proto_forward_proto_rawDescGZIP() []byte {
	file_internal_connector_proto_forward_proto_rawDescOnce.Do(func() {
		file_internal_connector_proto_forward_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_connector_proto_forward_proto_rawDesc), len(file_internal_connector_proto_forward_proto_rawDesc)))
	})
	return file_internal_connector_proto_forward_proto_rawDescData
}

var file_internal_connector_proto_forward_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_connector_proto_forward_proto_goTypes = []any{
	(*ForwardRequest)(nil),  // 0: connector.ForwardRequest
	(*ForwardResponse)(nil), // 1: connector.ForwardResponse
	nil,                     // 2: connector.ForwardRequest.HeadersEntry
}
var file_internal_connector_proto_forward_proto_depIdxs = []int32{
	2, // 0: connector.ForwardRequest.headers:type_name -> connector.ForwardRequest.HeadersEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_connector_proto_forward_proto_init() }
func file_internal_connector_proto_forward_proto_init() {
	if File_internal_connector_proto_forward_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_connector_proto_forward_proto_rawDesc), len(file_internal_connector_proto_forward_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_connector_proto_forward_proto_goTypes,
		DependencyIndexes: file_internal_connector_proto_forward_proto_depIdxs,
		MessageInfos:      file_internal_connector_proto_forward_proto_msgTypes,
	}.Build()
	File_internal_connector_proto_forward_proto = out.File
	file_internal_connector_proto_forward_proto_goTypes = nil
	file_internal_connector_proto_forward_proto_depIdxs = nil
}
