// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: internal/connector/proto/forward.proto

package connector

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OutputConnector_Init_FullMethodName        = "/keel.connector.OutputConnector/Init"
	OutputConnector_Forward_FullMethodName     = "/keel.connector.OutputConnector/Forward"
	OutputConnector_HealthCheck_FullMethodName = "/keel.connector.OutputConnector/HealthCheck"
	OutputConnector_Shutdown_FullMethodName    = "/keel.connector.OutputConnector/Shutdown"
)

// OutputConnectorClient is the client API for OutputConnector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OutputConnector is the gRPC contract between the broker (host) and an
// output connector — whether the connector runs in-process (built into
// this binary, e.g. kafka-hono) or out-of-process as a sidecar plugin
// (hashicorp/go-plugin, see internal/connector/pluginhost). It mirrors the
// connector.OutputConnector Go interface exactly, one RPC per method, so a
// call site never needs to know which transport backs a given connector.
type OutputConnectorClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*Empty, error)
	Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error)
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type outputConnectorClient struct {
	cc grpc.ClientConnInterface
}

func NewOutputConnectorClient(cc grpc.ClientConnInterface) OutputConnectorClient {
	return &outputConnectorClient{cc}
}

func (c *outputConnectorClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, OutputConnector_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outputConnectorClient) Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardResponse)
	err := c.cc.Invoke(ctx, OutputConnector_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outputConnectorClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, OutputConnector_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outputConnectorClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, OutputConnector_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutputConnectorServer is the server API for OutputConnector service.
// All implementations must embed UnimplementedOutputConnectorServer
// for forward compatibility.
//
// OutputConnector is the gRPC contract between the broker (host) and an
// output connector — whether the connector runs in-process (built into
// this binary, e.g. kafka-hono) or out-of-process as a sidecar plugin
// (hashicorp/go-plugin, see internal/connector/pluginhost). It mirrors the
// connector.OutputConnector Go interface exactly, one RPC per method, so a
// call site never needs to know which transport backs a given connector.
type OutputConnectorServer interface {
	Init(context.Context, *InitRequest) (*Empty, error)
	Forward(context.Context, *ForwardRequest) (*ForwardResponse, error)
	HealthCheck(context.Context, *Empty) (*Empty, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedOutputConnectorServer()
}

// UnimplementedOutputConnectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOutputConnectorServer struct{}

func (UnimplementedOutputConnectorServer) Init(context.Context, *InitRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedOutputConnectorServer) Forward(context.Context, *ForwardRequest) (*ForwardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedOutputConnectorServer) HealthCheck(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedOutputConnectorServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedOutputConnectorServer) mustEmbedUnimplementedOutputConnectorServer() {}
func (UnimplementedOutputConnectorServer) testEmbeddedByValue()                         {}

// UnsafeOutputConnectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutputConnectorServer will
// result in compilation errors.
type UnsafeOutputConnectorServer interface {
	mustEmbedUnimplementedOutputConnectorServer()
}

func RegisterOutputConnectorServer(s grpc.ServiceRegistrar, srv OutputConnectorServer) {
	// If the following call panics, it indicates UnimplementedOutputConnectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OutputConnector_ServiceDesc, srv)
}

func _OutputConnector_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputConnectorServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutputConnector_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputConnectorServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutputConnector_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputConnectorServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutputConnector_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputConnectorServer).Forward(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutputConnector_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputConnectorServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutputConnector_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputConnectorServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutputConnector_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputConnectorServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutputConnector_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputConnectorServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// OutputConnector_ServiceDesc is the grpc.ServiceDesc for OutputConnector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutputConnector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keel.connector.OutputConnector",
	HandlerType: (*OutputConnectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _OutputConnector_Init_Handler,
		},
		{
			MethodName: "Forward",
			Handler:    _OutputConnector_Forward_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _OutputConnector_HealthCheck_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _OutputConnector_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/connector/proto/forward.proto",
}
