// Package dataplane carries MQTT message payloads directly between nodes,
// kept off the raft log (which only replicates routing/session control
// state — see internal/cluster/raft). Phase 1 implements Forwarder with
// point-to-point gRPC; the interface is designed so an embedded-NATS
// implementation can be dropped in later without touching callers.
package dataplane

import "github.com/google/uuid"

// Message is a single MQTT publish being routed to a remote node because
// that node owns a client subscribed to the topic (per
// raft.Registry.NodesFor).
type Message struct {
	SourceNodeID string
	TenantID     string
	Topic        string
	Payload      []byte
	QoS          byte
	// PublishID identifies this MQTT PUBLISH event, not its content —
	// generated once by the node that received it from mochi-mqtt, never
	// regenerated by a forward. Internal to Keel's own delivery dedup
	// (see internal/broker's offline-delivery dedup), not an MQTT
	// protocol field, not a Packet ID, not an application message ID.
	PublishID uuid.UUID
}
