package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/google/uuid"
	"gopkg.in/yaml.v3"
)

// fixedPasswordHash is the bcrypt hash of "testpass123" already used by
// deploy/docker-compose/credentials.yaml for the e2e test devices. Reusing
// the literal instead of hashing per-device avoids N bcrypt hashes (cost 10,
// ~60ms each) at generation time for potentially thousands of devices — the
// hash is identical for every device anyway since they all share one
// password, exactly like the existing e2e fixture.
const (
	fixedPassword     = "testpass123"
	fixedPasswordHash = "$2a$10$qg4iMKaWEPTUwuB7ekeutu5r9B1cRK6TtoemXJUmVsaXaqfUmOYCq"
)

type credEntry struct {
	DeviceID     string `yaml:"device_id"`
	TenantID     string `yaml:"tenant_id"`
	TenantSlug   string `yaml:"tenant_slug"`
	PasswordHash string `yaml:"password_hash"`
}

type credFile struct {
	Devices []credEntry `yaml:"devices"`
}

func runGenCredentials(args []string) {
	fs := flag.NewFlagSet("gen-credentials", flag.ExitOnError)
	count := fs.Int("count", 200, "number of simulated devices to generate")
	tenantID := fs.String("tenant-id", "22222222-2222-2222-2222-222222222222", "tenant UUID shared by all simulated devices")
	tenantSlug := fs.String("tenant-slug", "devicesim", "tenant slug shared by all simulated devices")
	out := fs.String("out", "deploy/docker-compose/credentials.devicesim.yaml", "output YAML path")
	idsOut := fs.String("ids-out", "", "optional: also write the plain list of generated device UUIDs, one per line (used by 'run --device-ids-file')")
	merge := fs.String("merge-with", "", "optional: existing credentials.yaml to merge with (its devices are kept, simulated devices appended) so the same file can still serve the e2e fixtures")
	_ = fs.Parse(args)

	if *count <= 0 {
		fmt.Fprintln(os.Stderr, "gen-credentials: -count must be > 0")
		os.Exit(2)
	}

	cf := credFile{}
	if *merge != "" {
		data, err := os.ReadFile(*merge)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gen-credentials: read -merge-with: %v\n", err)
			os.Exit(1)
		}
		if err := yaml.Unmarshal(data, &cf); err != nil {
			fmt.Fprintf(os.Stderr, "gen-credentials: parse -merge-with: %v\n", err)
			os.Exit(1)
		}
	}

	ids := make([]string, *count)
	for i := 0; i < *count; i++ {
		id := uuid.New().String()
		ids[i] = id
		cf.Devices = append(cf.Devices, credEntry{
			DeviceID:     id,
			TenantID:     *tenantID,
			TenantSlug:   *tenantSlug,
			PasswordHash: fixedPasswordHash,
		})
	}

	data, err := yaml.Marshal(cf)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-credentials: marshal: %v\n", err)
		os.Exit(1)
	}
	header := fmt.Sprintf("# Generated by devicesim gen-credentials — %d simulated devices, tenant %s (%s).\n# All devices share the password %q. Do not use in production.\n", *count, *tenantSlug, *tenantID, fixedPassword)
	if err := os.WriteFile(*out, []byte(header+string(data)), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-credentials: write %s: %v\n", *out, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %d devices (tenant %s) to %s\n", *count, *tenantID, *out)

	if *idsOut != "" {
		f, err := os.Create(*idsOut)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gen-credentials: write %s: %v\n", *idsOut, err)
			os.Exit(1)
		}
		defer f.Close()
		for _, id := range ids {
			fmt.Fprintln(f, id)
		}
		fmt.Printf("wrote %d device IDs to %s\n", *count, *idsOut)
	}
}
