// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: internal/cluster/proto/cluster.proto

package clusterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{1}
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *UnsubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *UnsubscribeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type UnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{3}
}

type NodesForRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Topic string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// local_node_id is the caller's own node ID. For a shared-subscription
	// group ($share/group/filter) whose only match is a local client on
	// this node, the caller already gets the message via its own local
	// mochi-mqtt delivery — so the registry excludes it from the returned
	// set and, if the group has other members, picks exactly one of those
	// instead, to preserve exactly-once delivery per group.
	LocalNodeId   string `protobuf:"bytes,2,opt,name=local_node_id,json=localNodeId,proto3" json:"local_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodesForRequest) Reset() {
	*x = NodesForRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodesForRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesForRequest) ProtoMessage() {}

func (x *NodesForRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesForRequest.ProtoReflect.Descriptor instead.
func (*NodesForRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *NodesForRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *NodesForRequest) GetLocalNodeId() string {
	if x != nil {
		return x.LocalNodeId
	}
	return ""
}

type NodesForResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIds       []string               `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodesForResponse) Reset() {
	*x = NodesForResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodesForResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesForResponse) ProtoMessage() {}

func (x *NodesForResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesForResponse.ProtoReflect.Descriptor instead.
func (*NodesForResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *NodesForResponse) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type ClaimSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimSessionRequest) Reset() {
	*x = ClaimSessionRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimSessionRequest) ProtoMessage() {}

func (x *ClaimSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimSessionRequest.ProtoReflect.Descriptor instead.
func (*ClaimSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimSessionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClaimSessionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ClaimSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// evicted_node_id is the previous owner's node ID when the claim took
	// the session over from a different node, empty otherwise — see
	// raft.Registry.ClaimSession's doc.
	EvictedNodeId string `protobuf:"bytes,2,opt,name=evicted_node_id,json=evictedNodeId,proto3" json:"evicted_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimSessionResponse) Reset() {
	*x = ClaimSessionResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimSessionResponse) ProtoMessage() {}

func (x *ClaimSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimSessionResponse.ProtoReflect.Descriptor instead.
func (*ClaimSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *ClaimSessionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ClaimSessionResponse) GetEvictedNodeId() string {
	if x != nil {
		return x.EvictedNodeId
	}
	return ""
}

type ReleaseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSessionRequest) Reset() {
	*x = ReleaseSessionRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSessionRequest) ProtoMessage() {}

func (x *ReleaseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSessionRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseSessionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReleaseSessionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ReleaseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSessionResponse) Reset() {
	*x = ReleaseSessionResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSessionResponse) ProtoMessage() {}

func (x *ReleaseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSessionResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{9}
}

type EvaluateACLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"` // "publish" | "subscribe"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateACLRequest) Reset() {
	*x = EvaluateACLRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateACLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateACLRequest) ProtoMessage() {}

func (x *EvaluateACLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateACLRequest.ProtoReflect.Descriptor instead.
func (*EvaluateACLRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *EvaluateACLRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *EvaluateACLRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EvaluateACLRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *EvaluateACLRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type EvaluateACLResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Allowed bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// matched_filter is the topic filter of the rule that decided the
	// outcome, empty when the decision was the fail-closed default (no
	// rule matched). Carried across the wire for audit/debugging parity
	// with acl.Decision on the core side.
	MatchedFilter string `protobuf:"bytes,2,opt,name=matched_filter,json=matchedFilter,proto3" json:"matched_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateACLResponse) Reset() {
	*x = EvaluateACLResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateACLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateACLResponse) ProtoMessage() {}

func (x *EvaluateACLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateACLResponse.ProtoReflect.Descriptor instead.
func (*EvaluateACLResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *EvaluateACLResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *EvaluateACLResponse) GetMatchedFilter() string {
	if x != nil {
		return x.MatchedFilter
	}
	return ""
}

type ACLRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicFilter   string                 `protobuf:"bytes,1,opt,name=topic_filter,json=topicFilter,proto3" json:"topic_filter,omitempty"`
	Actions       []string               `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	Effect        string                 `protobuf:"bytes,3,opt,name=effect,proto3" json:"effect,omitempty"` // "allow" | "deny"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACLRule) Reset() {
	*x = ACLRule{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACLRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACLRule) ProtoMessage() {}

func (x *ACLRule) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACLRule.ProtoReflect.Descriptor instead.
func (*ACLRule) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *ACLRule) GetTopicFilter() string {
	if x != nil {
		return x.TopicFilter
	}
	return ""
}

func (x *ACLRule) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ACLRule) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

type ACLSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACLSnapshotRequest) Reset() {
	*x = ACLSnapshotRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACLSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACLSnapshotRequest) ProtoMessage() {}

func (x *ACLSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACLSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ACLSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{13}
}

type RoleEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rules         []*ACLRule             `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleEntry) Reset() {
	*x = RoleEntry{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleEntry) ProtoMessage() {}

func (x *RoleEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleEntry.ProtoReflect.Descriptor instead.
func (*RoleEntry) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{14}
}

func (x *RoleEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleEntry) GetRules() []*ACLRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type BindingEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     string                 `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	RoleNames     []string               `protobuf:"bytes,2,rep,name=role_names,json=roleNames,proto3" json:"role_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindingEntry) Reset() {
	*x = BindingEntry{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingEntry) ProtoMessage() {}

func (x *BindingEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindingEntry.ProtoReflect.Descriptor instead.
func (*BindingEntry) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{15}
}

func (x *BindingEntry) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *BindingEntry) GetRoleNames() []string {
	if x != nil {
		return x.RoleNames
	}
	return nil
}

type ACLSnapshotResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Roles           []*RoleEntry           `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Bindings        []*BindingEntry        `protobuf:"bytes,2,rep,name=bindings,proto3" json:"bindings,omitempty"`
	EnabledRulesets []string               `protobuf:"bytes,3,rep,name=enabled_rulesets,json=enabledRulesets,proto3" json:"enabled_rulesets,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ACLSnapshotResponse) Reset() {
	*x = ACLSnapshotResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACLSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACLSnapshotResponse) ProtoMessage() {}

func (x *ACLSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACLSnapshotResponse.ProtoReflect.Descriptor instead.
func (*ACLSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{16}
}

func (x *ACLSnapshotResponse) GetRoles() []*RoleEntry {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ACLSnapshotResponse) GetBindings() []*BindingEntry {
	if x != nil {
		return x.Bindings
	}
	return nil
}

func (x *ACLSnapshotResponse) GetEnabledRulesets() []string {
	if x != nil {
		return x.EnabledRulesets
	}
	return nil
}

type CurrentRedisPrimaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentRedisPrimaryRequest) Reset() {
	*x = CurrentRedisPrimaryRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentRedisPrimaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentRedisPrimaryRequest) ProtoMessage() {}

func (x *CurrentRedisPrimaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentRedisPrimaryRequest.ProtoReflect.Descriptor instead.
func (*CurrentRedisPrimaryRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{17}
}

type CurrentRedisPrimaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"` // false when no primary has ever been designated yet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentRedisPrimaryResponse) Reset() {
	*x = CurrentRedisPrimaryResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentRedisPrimaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentRedisPrimaryResponse) ProtoMessage() {}

func (x *CurrentRedisPrimaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentRedisPrimaryResponse.ProtoReflect.Descriptor instead.
func (*CurrentRedisPrimaryResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{18}
}

func (x *CurrentRedisPrimaryResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CurrentRedisPrimaryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rules         []*ACLRule             `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{19}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetRules() []*ACLRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{20}
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{22}
}

type CreateBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     string                 `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBindingRequest) Reset() {
	*x = CreateBindingRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBindingRequest) ProtoMessage() {}

func (x *CreateBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBindingRequest.ProtoReflect.Descriptor instead.
func (*CreateBindingRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{23}
}

func (x *CreateBindingRequest) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *CreateBindingRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type CreateBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBindingResponse) Reset() {
	*x = CreateBindingResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBindingResponse) ProtoMessage() {}

func (x *CreateBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBindingResponse.ProtoReflect.Descriptor instead.
func (*CreateBindingResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{24}
}

type DeleteBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     string                 `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBindingRequest) Reset() {
	*x = DeleteBindingRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBindingRequest) ProtoMessage() {}

func (x *DeleteBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBindingRequest.ProtoReflect.Descriptor instead.
func (*DeleteBindingRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteBindingRequest) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *DeleteBindingRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type DeleteBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBindingResponse) Reset() {
	*x = DeleteBindingResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBindingResponse) ProtoMessage() {}

func (x *DeleteBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBindingResponse.ProtoReflect.Descriptor instead.
func (*DeleteBindingResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{26}
}

type EnableRulesetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRulesetRequest) Reset() {
	*x = EnableRulesetRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRulesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRulesetRequest) ProtoMessage() {}

func (x *EnableRulesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRulesetRequest.ProtoReflect.Descriptor instead.
func (*EnableRulesetRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{27}
}

func (x *EnableRulesetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnableRulesetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRulesetResponse) Reset() {
	*x = EnableRulesetResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRulesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRulesetResponse) ProtoMessage() {}

func (x *EnableRulesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRulesetResponse.ProtoReflect.Descriptor instead.
func (*EnableRulesetResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{28}
}

type DisableRulesetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableRulesetRequest) Reset() {
	*x = DisableRulesetRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableRulesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRulesetRequest) ProtoMessage() {}

func (x *DisableRulesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRulesetRequest.ProtoReflect.Descriptor instead.
func (*DisableRulesetRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{29}
}

func (x *DisableRulesetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DisableRulesetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableRulesetResponse) Reset() {
	*x = DisableRulesetResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableRulesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRulesetResponse) ProtoMessage() {}

func (x *DisableRulesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRulesetResponse.ProtoReflect.Descriptor instead.
func (*DisableRulesetResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{30}
}

type ForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeId  string                 `protobuf:"bytes,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Qos           uint32                 `protobuf:"varint,5,opt,name=qos,proto3" json:"qos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{31}
}

func (x *ForwardRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *ForwardRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ForwardRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ForwardRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ForwardRequest) GetQos() uint32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

type ForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{32}
}

type EvictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictRequest) Reset() {
	*x = EvictRequest{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictRequest) ProtoMessage() {}

func (x *EvictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictRequest.ProtoReflect.Descriptor instead.
func (*EvictRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{33}
}

func (x *EvictRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type EvictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictResponse) Reset() {
	*x = EvictResponse{}
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictResponse) ProtoMessage() {}

func (x *EvictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_cluster_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictResponse.ProtoReflect.Descriptor instead.
func (*EvictResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_cluster_proto_rawDescGZIP(), []int{34}
}

var File_internal_cluster_proto_cluster_proto protoreflect.FileDescriptor

const file_internal_cluster_proto_cluster_proto_rawDesc = "" +
	"\n" +
	"$internal/cluster/proto/cluster.proto\x12\fkeel.cluster\"A\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"\x13\n" +
	"\x11SubscribeResponse\"C\n" +
	"\x12UnsubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"\x15\n" +
	"\x13UnsubscribeResponse\"K\n" +
	"\x0fNodesForRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\"\n" +
	"\rlocal_node_id\x18\x02 \x01(\tR\vlocalNodeId\"-\n" +
	"\x10NodesForResponse\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\tR\anodeIds\"K\n" +
	"\x13ClaimSessionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"N\n" +
	"\x14ClaimSessionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12&\n" +
	"\x0fevicted_node_id\x18\x02 \x01(\tR\revictedNodeId\"M\n" +
	"\x15ReleaseSessionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"\x18\n" +
	"\x16ReleaseSessionResponse\"{\n" +
	"\x12EvaluateACLRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"V\n" +
	"\x13EvaluateACLResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12%\n" +
	"\x0ematched_filter\x18\x02 \x01(\tR\rmatchedFilter\"^\n" +
	"\aACLRule\x12!\n" +
	"\ftopic_filter\x18\x01 \x01(\tR\vtopicFilter\x12\x18\n" +
	"\aactions\x18\x02 \x03(\tR\aactions\x12\x16\n" +
	"\x06effect\x18\x03 \x01(\tR\x06effect\"\x14\n" +
	"\x12ACLSnapshotRequest\"L\n" +
	"\tRoleEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x05rules\x18\x02 \x03(\v2\x15.keel.cluster.ACLRuleR\x05rules\"K\n" +
	"\fBindingEntry\x12\x1c\n" +
	"\tprincipal\x18\x01 \x01(\tR\tprincipal\x12\x1d\n" +
	"\n" +
	"role_names\x18\x02 \x03(\tR\troleNames\"\xa7\x01\n" +
	"\x13ACLSnapshotResponse\x12-\n" +
	"\x05roles\x18\x01 \x03(\v2\x17.keel.cluster.RoleEntryR\x05roles\x126\n" +
	"\bbindings\x18\x02 \x03(\v2\x1a.keel.cluster.BindingEntryR\bbindings\x12)\n" +
	"\x10enabled_rulesets\x18\x03 \x03(\tR\x0fenabledRulesets\"\x1c\n" +
	"\x1aCurrentRedisPrimaryRequest\"F\n" +
	"\x1bCurrentRedisPrimaryResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"T\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x05rules\x18\x02 \x03(\v2\x15.keel.cluster.ACLRuleR\x05rules\"\x14\n" +
	"\x12CreateRoleResponse\"'\n" +
	"\x11DeleteRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x14\n" +
	"\x12DeleteRoleResponse\"Q\n" +
	"\x14CreateBindingRequest\x12\x1c\n" +
	"\tprincipal\x18\x01 \x01(\tR\tprincipal\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\"\x17\n" +
	"\x15CreateBindingResponse\"Q\n" +
	"\x14DeleteBindingRequest\x12\x1c\n" +
	"\tprincipal\x18\x01 \x01(\tR\tprincipal\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\"\x17\n" +
	"\x15DeleteBindingResponse\"*\n" +
	"\x14EnableRulesetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x17\n" +
	"\x15EnableRulesetResponse\"+\n" +
	"\x15DisableRulesetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x18\n" +
	"\x16DisableRulesetResponse\"\x95\x01\n" +
	"\x0eForwardRequest\x12$\n" +
	"\x0esource_node_id\x18\x01 \x01(\tR\fsourceNodeId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x10\n" +
	"\x03qos\x18\x05 \x01(\rR\x03qos\"\x11\n" +
	"\x0fForwardResponse\"+\n" +
	"\fEvictRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\x0f\n" +
	"\rEvictResponse2\xcc\t\n" +
	"\bRegistry\x12L\n" +
	"\tSubscribe\x12\x1e.keel.cluster.SubscribeRequest\x1a\x1f.keel.cluster.SubscribeResponse\x12R\n" +
	"\vUnsubscribe\x12 .keel.cluster.UnsubscribeRequest\x1a!.keel.cluster.UnsubscribeResponse\x12I\n" +
	"\bNodesFor\x12\x1d.keel.cluster.NodesForRequest\x1a\x1e.keel.cluster.NodesForResponse\x12U\n" +
	"\fClaimSession\x12!.keel.cluster.ClaimSessionRequest\x1a\".keel.cluster.ClaimSessionResponse\x12[\n" +
	"\x0eReleaseSession\x12#.keel.cluster.ReleaseSessionRequest\x1a$.keel.cluster.ReleaseSessionResponse\x12R\n" +
	"\vEvaluateACL\x12 .keel.cluster.EvaluateACLRequest\x1a!.keel.cluster.EvaluateACLResponse\x12R\n" +
	"\vACLSnapshot\x12 .keel.cluster.ACLSnapshotRequest\x1a!.keel.cluster.ACLSnapshotResponse\x12j\n" +
	"\x13CurrentRedisPrimary\x12(.keel.cluster.CurrentRedisPrimaryRequest\x1a).keel.cluster.CurrentRedisPrimaryResponse\x12O\n" +
	"\n" +
	"CreateRole\x12\x1f.keel.cluster.CreateRoleRequest\x1a .keel.cluster.CreateRoleResponse\x12O\n" +
	"\n" +
	"DeleteRole\x12\x1f.keel.cluster.DeleteRoleRequest\x1a .keel.cluster.DeleteRoleResponse\x12X\n" +
	"\rCreateBinding\x12\".keel.cluster.CreateBindingRequest\x1a#.keel.cluster.CreateBindingResponse\x12X\n" +
	"\rDeleteBinding\x12\".keel.cluster.DeleteBindingRequest\x1a#.keel.cluster.DeleteBindingResponse\x12X\n" +
	"\rEnableRuleset\x12\".keel.cluster.EnableRulesetRequest\x1a#.keel.cluster.EnableRulesetResponse\x12[\n" +
	"\x0eDisableRuleset\x12#.keel.cluster.DisableRulesetRequest\x1a$.keel.cluster.DisableRulesetResponse2\x95\x01\n" +
	"\tDataplane\x12F\n" +
	"\aForward\x12\x1c.keel.cluster.ForwardRequest\x1a\x1d.keel.cluster.ForwardResponse\x12@\n" +
	"\x05Evict\x12\x1a.keel.cluster.EvictRequest\x1a\x1b.keel.cluster.EvictResponseBHZFgithub.com/keel-iot/keel-mqtt-gateway/internal/cluster/proto/clusterpbb\x06proto3"

var (
	file_internal_cluster_proto_cluster_proto_rawDescOnce sync.Once
	file_internal_cluster_proto_cluster_proto_rawDescData []byte
)

func file_internal_cluster_proto_cluster_proto_rawDescGZIP() []byte {
	file_internal_cluster_proto_cluster_proto_rawDescOnce.Do(func() {
		file_internal_cluster_proto_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_cluster_proto_cluster_proto_rawDesc), len(file_internal_cluster_proto_cluster_proto_rawDesc)))
	})
	return file_internal_cluster_proto_cluster_proto_rawDescData
}

var file_internal_cluster_proto_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_internal_cluster_proto_cluster_proto_goTypes = []any{
	(*SubscribeRequest)(nil),            // 0: keel.cluster.SubscribeRequest
	(*SubscribeResponse)(nil),           // 1: keel.cluster.SubscribeResponse
	(*UnsubscribeRequest)(nil),          // 2: keel.cluster.UnsubscribeRequest
	(*UnsubscribeResponse)(nil),         // 3: keel.cluster.UnsubscribeResponse
	(*NodesForRequest)(nil),             // 4: keel.cluster.NodesForRequest
	(*NodesForResponse)(nil),            // 5: keel.cluster.NodesForResponse
	(*ClaimSessionRequest)(nil),         // 6: keel.cluster.ClaimSessionRequest
	(*ClaimSessionResponse)(nil),        // 7: keel.cluster.ClaimSessionResponse
	(*ReleaseSessionRequest)(nil),       // 8: keel.cluster.ReleaseSessionRequest
	(*ReleaseSessionResponse)(nil),      // 9: keel.cluster.ReleaseSessionResponse
	(*EvaluateACLRequest)(nil),          // 10: keel.cluster.EvaluateACLRequest
	(*EvaluateACLResponse)(nil),         // 11: keel.cluster.EvaluateACLResponse
	(*ACLRule)(nil),                     // 12: keel.cluster.ACLRule
	(*ACLSnapshotRequest)(nil),          // 13: keel.cluster.ACLSnapshotRequest
	(*RoleEntry)(nil),                   // 14: keel.cluster.RoleEntry
	(*BindingEntry)(nil),                // 15: keel.cluster.BindingEntry
	(*ACLSnapshotResponse)(nil),         // 16: keel.cluster.ACLSnapshotResponse
	(*CurrentRedisPrimaryRequest)(nil),  // 17: keel.cluster.CurrentRedisPrimaryRequest
	(*CurrentRedisPrimaryResponse)(nil), // 18: keel.cluster.CurrentRedisPrimaryResponse
	(*CreateRoleRequest)(nil),           // 19: keel.cluster.CreateRoleRequest
	(*CreateRoleResponse)(nil),          // 20: keel.cluster.CreateRoleResponse
	(*DeleteRoleRequest)(nil),           // 21: keel.cluster.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),          // 22: keel.cluster.DeleteRoleResponse
	(*CreateBindingRequest)(nil),        // 23: keel.cluster.CreateBindingRequest
	(*CreateBindingResponse)(nil),       // 24: keel.cluster.CreateBindingResponse
	(*DeleteBindingRequest)(nil),        // 25: keel.cluster.DeleteBindingRequest
	(*DeleteBindingResponse)(nil),       // 26: keel.cluster.DeleteBindingResponse
	(*EnableRulesetRequest)(nil),        // 27: keel.cluster.EnableRulesetRequest
	(*EnableRulesetResponse)(nil),       // 28: keel.cluster.EnableRulesetResponse
	(*DisableRulesetRequest)(nil),       // 29: keel.cluster.DisableRulesetRequest
	(*DisableRulesetResponse)(nil),      // 30: keel.cluster.DisableRulesetResponse
	(*ForwardRequest)(nil),              // 31: keel.cluster.ForwardRequest
	(*ForwardResponse)(nil),             // 32: keel.cluster.ForwardResponse
	(*EvictRequest)(nil),                // 33: keel.cluster.EvictRequest
	(*EvictResponse)(nil),               // 34: keel.cluster.EvictResponse
}
var file_internal_cluster_proto_cluster_proto_depIdxs = []int32{
	12, // 0: keel.cluster.RoleEntry.rules:type_name -> keel.cluster.ACLRule
	14, // 1: keel.cluster.ACLSnapshotResponse.roles:type_name -> keel.cluster.RoleEntry
	15, // 2: keel.cluster.ACLSnapshotResponse.bindings:type_name -> keel.cluster.BindingEntry
	12, // 3: keel.cluster.CreateRoleRequest.rules:type_name -> keel.cluster.ACLRule
	0,  // 4: keel.cluster.Registry.Subscribe:input_type -> keel.cluster.SubscribeRequest
	2,  // 5: keel.cluster.Registry.Unsubscribe:input_type -> keel.cluster.UnsubscribeRequest
	4,  // 6: keel.cluster.Registry.NodesFor:input_type -> keel.cluster.NodesForRequest
	6,  // 7: keel.cluster.Registry.ClaimSession:input_type -> keel.cluster.ClaimSessionRequest
	8,  // 8: keel.cluster.Registry.ReleaseSession:input_type -> keel.cluster.ReleaseSessionRequest
	10, // 9: keel.cluster.Registry.EvaluateACL:input_type -> keel.cluster.EvaluateACLRequest
	13, // 10: keel.cluster.Registry.ACLSnapshot:input_type -> keel.cluster.ACLSnapshotRequest
	17, // 11: keel.cluster.Registry.CurrentRedisPrimary:input_type -> keel.cluster.CurrentRedisPrimaryRequest
	19, // 12: keel.cluster.Registry.CreateRole:input_type -> keel.cluster.CreateRoleRequest
	21, // 13: keel.cluster.Registry.DeleteRole:input_type -> keel.cluster.DeleteRoleRequest
	23, // 14: keel.cluster.Registry.CreateBinding:input_type -> keel.cluster.CreateBindingRequest
	25, // 15: keel.cluster.Registry.DeleteBinding:input_type -> keel.cluster.DeleteBindingRequest
	27, // 16: keel.cluster.Registry.EnableRuleset:input_type -> keel.cluster.EnableRulesetRequest
	29, // 17: keel.cluster.Registry.DisableRuleset:input_type -> keel.cluster.DisableRulesetRequest
	31, // 18: keel.cluster.Dataplane.Forward:input_type -> keel.cluster.ForwardRequest
	33, // 19: keel.cluster.Dataplane.Evict:input_type -> keel.cluster.EvictRequest
	1,  // 20: keel.cluster.Registry.Subscribe:output_type -> keel.cluster.SubscribeResponse
	3,  // 21: keel.cluster.Registry.Unsubscribe:output_type -> keel.cluster.UnsubscribeResponse
	5,  // 22: keel.cluster.Registry.NodesFor:output_type -> keel.cluster.NodesForResponse
	7,  // 23: keel.cluster.Registry.ClaimSession:output_type -> keel.cluster.ClaimSessionResponse
	9,  // 24: keel.cluster.Registry.ReleaseSession:output_type -> keel.cluster.ReleaseSessionResponse
	11, // 25: keel.cluster.Registry.EvaluateACL:output_type -> keel.cluster.EvaluateACLResponse
	16, // 26: keel.cluster.Registry.ACLSnapshot:output_type -> keel.cluster.ACLSnapshotResponse
	18, // 27: keel.cluster.Registry.CurrentRedisPrimary:output_type -> keel.cluster.CurrentRedisPrimaryResponse
	20, // 28: keel.cluster.Registry.CreateRole:output_type -> keel.cluster.CreateRoleResponse
	22, // 29: keel.cluster.Registry.DeleteRole:output_type -> keel.cluster.DeleteRoleResponse
	24, // 30: keel.cluster.Registry.CreateBinding:output_type -> keel.cluster.CreateBindingResponse
	26, // 31: keel.cluster.Registry.DeleteBinding:output_type -> keel.cluster.DeleteBindingResponse
	28, // 32: keel.cluster.Registry.EnableRuleset:output_type -> keel.cluster.EnableRulesetResponse
	30, // 33: keel.cluster.Registry.DisableRuleset:output_type -> keel.cluster.DisableRulesetResponse
	32, // 34: keel.cluster.Dataplane.Forward:output_type -> keel.cluster.ForwardResponse
	34, // 35: keel.cluster.Dataplane.Evict:output_type -> keel.cluster.EvictResponse
	20, // [20:36] is the sub-list for method output_type
	4,  // [4:20] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_cluster_proto_cluster_proto_init() }
func file_internal_cluster_proto_cluster_proto_init() {
	if File_internal_cluster_proto_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_cluster_proto_cluster_proto_rawDesc), len(file_internal_cluster_proto_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_cluster_proto_cluster_proto_goTypes,
		DependencyIndexes: file_internal_cluster_proto_cluster_proto_depIdxs,
		MessageInfos:      file_internal_cluster_proto_cluster_proto_msgTypes,
	}.Build()
	File_internal_cluster_proto_cluster_proto = out.File
	file_internal_cluster_proto_cluster_proto_goTypes = nil
	file_internal_cluster_proto_cluster_proto_depIdxs = nil
}
