// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: internal/cluster/proto/cluster.proto

package clusterpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Registry_Subscribe_FullMethodName           = "/keel.cluster.Registry/Subscribe"
	Registry_Unsubscribe_FullMethodName         = "/keel.cluster.Registry/Unsubscribe"
	Registry_NodesFor_FullMethodName            = "/keel.cluster.Registry/NodesFor"
	Registry_ClaimSession_FullMethodName        = "/keel.cluster.Registry/ClaimSession"
	Registry_ReleaseSession_FullMethodName      = "/keel.cluster.Registry/ReleaseSession"
	Registry_EvaluateACL_FullMethodName         = "/keel.cluster.Registry/EvaluateACL"
	Registry_ACLSnapshot_FullMethodName         = "/keel.cluster.Registry/ACLSnapshot"
	Registry_CurrentRedisPrimary_FullMethodName = "/keel.cluster.Registry/CurrentRedisPrimary"
	Registry_CreateRole_FullMethodName          = "/keel.cluster.Registry/CreateRole"
	Registry_DeleteRole_FullMethodName          = "/keel.cluster.Registry/DeleteRole"
	Registry_CreateBinding_FullMethodName       = "/keel.cluster.Registry/CreateBinding"
	Registry_DeleteBinding_FullMethodName       = "/keel.cluster.Registry/DeleteBinding"
	Registry_EnableRuleset_FullMethodName       = "/keel.cluster.Registry/EnableRuleset"
	Registry_DisableRuleset_FullMethodName      = "/keel.cluster.Registry/DisableRuleset"
	Registry_RevokeCertificate_FullMethodName   = "/keel.cluster.Registry/RevokeCertificate"
	Registry_IsRevoked_FullMethodName           = "/keel.cluster.Registry/IsRevoked"
	Registry_RevocationSnapshot_FullMethodName  = "/keel.cluster.Registry/RevocationSnapshot"
)

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Registry is called by edge nodes to reach the raft-backed Registry that
// lives on core nodes. Core nodes call their local LocalRegistry directly
// and never go through this RPC.
type RegistryClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error)
	NodesFor(ctx context.Context, in *NodesForRequest, opts ...grpc.CallOption) (*NodesForResponse, error)
	ClaimSession(ctx context.Context, in *ClaimSessionRequest, opts ...grpc.CallOption) (*ClaimSessionResponse, error)
	ReleaseSession(ctx context.Context, in *ReleaseSessionRequest, opts ...grpc.CallOption) (*ReleaseSessionResponse, error)
	// EvaluateACL is a read: any core node's FSM state is fail-closed-safe
	// to consult even if lagging slightly behind the leader (see
	// internal/cluster/acl and raft.LocalRegistry.EvaluateACL), so — like
	// NodesFor — it does not require reaching the leader specifically.
	EvaluateACL(ctx context.Context, in *EvaluateACLRequest, opts ...grpc.CallOption) (*EvaluateACLResponse, error)
	// ACLSnapshot is a read, same fail-closed-safe rationale as EvaluateACL
	// above — used by edge nodes to populate/refresh a local ACL cache
	// (internal/cluster/raft.ACLCache) instead of round-tripping
	// EvaluateACL to a core node on every publish/subscribe.
	ACLSnapshot(ctx context.Context, in *ACLSnapshotRequest, opts ...grpc.CallOption) (*ACLSnapshotResponse, error)
	// CurrentRedisPrimary is a read, same fail-closed-safe/any-peer
	// rationale as EvaluateACL/NodesFor — "who is the co-located Redis
	// primary" is decided via raft.Apply (see internal/cluster/raft's
	// OpSetRedisPrimary), not gossip, specifically so a leadership change
	// mid-failover can't cause two nodes to disagree; but READING that
	// decision never requires the leader specifically, same as any other
	// FSM read here. Used by every node running a
	// internal/cluster/redisrouter.Router (both core and edge) to redirect
	// to a new primary's address after a failover.
	CurrentRedisPrimary(ctx context.Context, in *CurrentRedisPrimaryRequest, opts ...grpc.CallOption) (*CurrentRedisPrimaryResponse, error)
	// ACL mutation RPCs. Only used core-to-core, when a non-leader core node
	// forwards a management-API-originated write to the current leader (the
	// same fallback path ClaimSession/ReleaseSession already use) — edge
	// nodes never call these directly, since internal/cluster/management is
	// only mounted on core nodes and the CLI/API always targets a core
	// address.
	CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error)
	DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*DeleteRoleResponse, error)
	CreateBinding(ctx context.Context, in *CreateBindingRequest, opts ...grpc.CallOption) (*CreateBindingResponse, error)
	DeleteBinding(ctx context.Context, in *DeleteBindingRequest, opts ...grpc.CallOption) (*DeleteBindingResponse, error)
	EnableRuleset(ctx context.Context, in *EnableRulesetRequest, opts ...grpc.CallOption) (*EnableRulesetResponse, error)
	DisableRuleset(ctx context.Context, in *DisableRulesetRequest, opts ...grpc.CallOption) (*DisableRulesetResponse, error)
	// RevokeCertificate is a write (same leader-only rationale as the ACL
	// mutations above) — records identity ("<deviceID>@<tenantID>", matches
	// the device cert's CN) as revoked. Called by the management API's
	// revocation webhook handler (see internal/cluster/management), itself
	// fed by an external custodian's revocation event (e.g. Clavex's
	// device.cert.revoked).
	RevokeCertificate(ctx context.Context, in *RevokeCertificateRequest, opts ...grpc.CallOption) (*RevokeCertificateResponse, error)
	// IsRevoked is a single-identity read, same fail-closed-on-transport-
	// -error rationale as EvaluateACL (an unreachable cluster must never
	// read as "not revoked"). Mirrors EvaluateACL/ACLSnapshot's split: this
	// is the live single-check RPC, RevocationSnapshot below is the bulk
	// fetch used to populate/refresh a local cache.
	IsRevoked(ctx context.Context, in *IsRevokedRequest, opts ...grpc.CallOption) (*IsRevokedResponse, error)
	// RevocationSnapshot is a read, same fail-closed-safe/any-peer
	// rationale as ACLSnapshot — used by every node (core and edge) to
	// populate/refresh a local revocation cache
	// (internal/cluster/raft.RevocationCache) instead of round-tripping
	// this RPC on every connect.
	RevocationSnapshot(ctx context.Context, in *RevocationSnapshotRequest, opts ...grpc.CallOption) (*RevocationSnapshotResponse, error)
}

type registryClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryClient(cc grpc.ClientConnInterface) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeResponse)
	err := c.cc.Invoke(ctx, Registry_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsubscribeResponse)
	err := c.cc.Invoke(ctx, Registry_Unsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) NodesFor(ctx context.Context, in *NodesForRequest, opts ...grpc.CallOption) (*NodesForResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodesForResponse)
	err := c.cc.Invoke(ctx, Registry_NodesFor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ClaimSession(ctx context.Context, in *ClaimSessionRequest, opts ...grpc.CallOption) (*ClaimSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimSessionResponse)
	err := c.cc.Invoke(ctx, Registry_ClaimSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ReleaseSession(ctx context.Context, in *ReleaseSessionRequest, opts ...grpc.CallOption) (*ReleaseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSessionResponse)
	err := c.cc.Invoke(ctx, Registry_ReleaseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) EvaluateACL(ctx context.Context, in *EvaluateACLRequest, opts ...grpc.CallOption) (*EvaluateACLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateACLResponse)
	err := c.cc.Invoke(ctx, Registry_EvaluateACL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ACLSnapshot(ctx context.Context, in *ACLSnapshotRequest, opts ...grpc.CallOption) (*ACLSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACLSnapshotResponse)
	err := c.cc.Invoke(ctx, Registry_ACLSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) CurrentRedisPrimary(ctx context.Context, in *CurrentRedisPrimaryRequest, opts ...grpc.CallOption) (*CurrentRedisPrimaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurrentRedisPrimaryResponse)
	err := c.cc.Invoke(ctx, Registry_CurrentRedisPrimary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoleResponse)
	err := c.cc.Invoke(ctx, Registry_CreateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*DeleteRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRoleResponse)
	err := c.cc.Invoke(ctx, Registry_DeleteRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) CreateBinding(ctx context.Context, in *CreateBindingRequest, opts ...grpc.CallOption) (*CreateBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBindingResponse)
	err := c.cc.Invoke(ctx, Registry_CreateBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) DeleteBinding(ctx context.Context, in *DeleteBindingRequest, opts ...grpc.CallOption) (*DeleteBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBindingResponse)
	err := c.cc.Invoke(ctx, Registry_DeleteBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) EnableRuleset(ctx context.Context, in *EnableRulesetRequest, opts ...grpc.CallOption) (*EnableRulesetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableRulesetResponse)
	err := c.cc.Invoke(ctx, Registry_EnableRuleset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) DisableRuleset(ctx context.Context, in *DisableRulesetRequest, opts ...grpc.CallOption) (*DisableRulesetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableRulesetResponse)
	err := c.cc.Invoke(ctx, Registry_DisableRuleset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) RevokeCertificate(ctx context.Context, in *RevokeCertificateRequest, opts ...grpc.CallOption) (*RevokeCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCertificateResponse)
	err := c.cc.Invoke(ctx, Registry_RevokeCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) IsRevoked(ctx context.Context, in *IsRevokedRequest, opts ...grpc.CallOption) (*IsRevokedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsRevokedResponse)
	err := c.cc.Invoke(ctx, Registry_IsRevoked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) RevocationSnapshot(ctx context.Context, in *RevocationSnapshotRequest, opts ...grpc.CallOption) (*RevocationSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevocationSnapshotResponse)
	err := c.cc.Invoke(ctx, Registry_RevocationSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServer is the server API for Registry service.
// All implementations must embed UnimplementedRegistryServer
// for forward compatibility.
//
// Registry is called by edge nodes to reach the raft-backed Registry that
// lives on core nodes. Core nodes call their local LocalRegistry directly
// and never go through this RPC.
type RegistryServer interface {
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error)
	NodesFor(context.Context, *NodesForRequest) (*NodesForResponse, error)
	ClaimSession(context.Context, *ClaimSessionRequest) (*ClaimSessionResponse, error)
	ReleaseSession(context.Context, *ReleaseSessionRequest) (*ReleaseSessionResponse, error)
	// EvaluateACL is a read: any core node's FSM state is fail-closed-safe
	// to consult even if lagging slightly behind the leader (see
	// internal/cluster/acl and raft.LocalRegistry.EvaluateACL), so — like
	// NodesFor — it does not require reaching the leader specifically.
	EvaluateACL(context.Context, *EvaluateACLRequest) (*EvaluateACLResponse, error)
	// ACLSnapshot is a read, same fail-closed-safe rationale as EvaluateACL
	// above — used by edge nodes to populate/refresh a local ACL cache
	// (internal/cluster/raft.ACLCache) instead of round-tripping
	// EvaluateACL to a core node on every publish/subscribe.
	ACLSnapshot(context.Context, *ACLSnapshotRequest) (*ACLSnapshotResponse, error)
	// CurrentRedisPrimary is a read, same fail-closed-safe/any-peer
	// rationale as EvaluateACL/NodesFor — "who is the co-located Redis
	// primary" is decided via raft.Apply (see internal/cluster/raft's
	// OpSetRedisPrimary), not gossip, specifically so a leadership change
	// mid-failover can't cause two nodes to disagree; but READING that
	// decision never requires the leader specifically, same as any other
	// FSM read here. Used by every node running a
	// internal/cluster/redisrouter.Router (both core and edge) to redirect
	// to a new primary's address after a failover.
	CurrentRedisPrimary(context.Context, *CurrentRedisPrimaryRequest) (*CurrentRedisPrimaryResponse, error)
	// ACL mutation RPCs. Only used core-to-core, when a non-leader core node
	// forwards a management-API-originated write to the current leader (the
	// same fallback path ClaimSession/ReleaseSession already use) — edge
	// nodes never call these directly, since internal/cluster/management is
	// only mounted on core nodes and the CLI/API always targets a core
	// address.
	CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleResponse, error)
	DeleteRole(context.Context, *DeleteRoleRequest) (*DeleteRoleResponse, error)
	CreateBinding(context.Context, *CreateBindingRequest) (*CreateBindingResponse, error)
	DeleteBinding(context.Context, *DeleteBindingRequest) (*DeleteBindingResponse, error)
	EnableRuleset(context.Context, *EnableRulesetRequest) (*EnableRulesetResponse, error)
	DisableRuleset(context.Context, *DisableRulesetRequest) (*DisableRulesetResponse, error)
	// RevokeCertificate is a write (same leader-only rationale as the ACL
	// mutations above) — records identity ("<deviceID>@<tenantID>", matches
	// the device cert's CN) as revoked. Called by the management API's
	// revocation webhook handler (see internal/cluster/management), itself
	// fed by an external custodian's revocation event (e.g. Clavex's
	// device.cert.revoked).
	RevokeCertificate(context.Context, *RevokeCertificateRequest) (*RevokeCertificateResponse, error)
	// IsRevoked is a single-identity read, same fail-closed-on-transport-
	// -error rationale as EvaluateACL (an unreachable cluster must never
	// read as "not revoked"). Mirrors EvaluateACL/ACLSnapshot's split: this
	// is the live single-check RPC, RevocationSnapshot below is the bulk
	// fetch used to populate/refresh a local cache.
	IsRevoked(context.Context, *IsRevokedRequest) (*IsRevokedResponse, error)
	// RevocationSnapshot is a read, same fail-closed-safe/any-peer
	// rationale as ACLSnapshot — used by every node (core and edge) to
	// populate/refresh a local revocation cache
	// (internal/cluster/raft.RevocationCache) instead of round-tripping
	// this RPC on every connect.
	RevocationSnapshot(context.Context, *RevocationSnapshotRequest) (*RevocationSnapshotResponse, error)
	mustEmbedUnimplementedRegistryServer()
}

// UnimplementedRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistryServer struct{}

func (UnimplementedRegistryServer) Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedRegistryServer) Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedRegistryServer) NodesFor(context.Context, *NodesForRequest) (*NodesForResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodesFor not implemented")
}
func (UnimplementedRegistryServer) ClaimSession(context.Context, *ClaimSessionRequest) (*ClaimSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimSession not implemented")
}
func (UnimplementedRegistryServer) ReleaseSession(context.Context, *ReleaseSessionRequest) (*ReleaseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSession not implemented")
}
func (UnimplementedRegistryServer) EvaluateACL(context.Context, *EvaluateACLRequest) (*EvaluateACLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateACL not implemented")
}
func (UnimplementedRegistryServer) ACLSnapshot(context.Context, *ACLSnapshotRequest) (*ACLSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ACLSnapshot not implemented")
}
func (UnimplementedRegistryServer) CurrentRedisPrimary(context.Context, *CurrentRedisPrimaryRequest) (*CurrentRedisPrimaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CurrentRedisPrimary not implemented")
}
func (UnimplementedRegistryServer) CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedRegistryServer) DeleteRole(context.Context, *DeleteRoleRequest) (*DeleteRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRole not implemented")
}
func (UnimplementedRegistryServer) CreateBinding(context.Context, *CreateBindingRequest) (*CreateBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBinding not implemented")
}
func (UnimplementedRegistryServer) DeleteBinding(context.Context, *DeleteBindingRequest) (*DeleteBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBinding not implemented")
}
func (UnimplementedRegistryServer) EnableRuleset(context.Context, *EnableRulesetRequest) (*EnableRulesetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableRuleset not implemented")
}
func (UnimplementedRegistryServer) DisableRuleset(context.Context, *DisableRulesetRequest) (*DisableRulesetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableRuleset not implemented")
}
func (UnimplementedRegistryServer) RevokeCertificate(context.Context, *RevokeCertificateRequest) (*RevokeCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeCertificate not implemented")
}
func (UnimplementedRegistryServer) IsRevoked(context.Context, *IsRevokedRequest) (*IsRevokedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsRevoked not implemented")
}
func (UnimplementedRegistryServer) RevocationSnapshot(context.Context, *RevocationSnapshotRequest) (*RevocationSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevocationSnapshot not implemented")
}
func (UnimplementedRegistryServer) mustEmbedUnimplementedRegistryServer() {}
func (UnimplementedRegistryServer) testEmbeddedByValue()                  {}

// UnsafeRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryServer will
// result in compilation errors.
type UnsafeRegistryServer interface {
	mustEmbedUnimplementedRegistryServer()
}

func RegisterRegistryServer(s grpc.ServiceRegistrar, srv RegistryServer) {
	// If the following call panics, it indicates UnimplementedRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Registry_ServiceDesc, srv)
}

func _Registry_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_NodesFor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodesForRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).NodesFor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_NodesFor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).NodesFor(ctx, req.(*NodesForRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ClaimSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ClaimSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_ClaimSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ClaimSession(ctx, req.(*ClaimSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ReleaseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ReleaseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_ReleaseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ReleaseSession(ctx, req.(*ReleaseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_EvaluateACL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateACLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).EvaluateACL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_EvaluateACL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).EvaluateACL(ctx, req.(*EvaluateACLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ACLSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ACLSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ACLSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_ACLSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ACLSnapshot(ctx, req.(*ACLSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_CurrentRedisPrimary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentRedisPrimaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).CurrentRedisPrimary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_CurrentRedisPrimary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).CurrentRedisPrimary(ctx, req.(*CurrentRedisPrimaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).CreateRole(ctx, req.(*CreateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_DeleteRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).DeleteRole(ctx, req.(*DeleteRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_CreateBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).CreateBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_CreateBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).CreateBinding(ctx, req.(*CreateBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_DeleteBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).DeleteBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_DeleteBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).DeleteBinding(ctx, req.(*DeleteBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_EnableRuleset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRulesetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).EnableRuleset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_EnableRuleset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).EnableRuleset(ctx, req.(*EnableRulesetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_DisableRuleset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableRulesetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).DisableRuleset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_DisableRuleset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).DisableRuleset(ctx, req.(*DisableRulesetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_RevokeCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).RevokeCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_RevokeCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).RevokeCertificate(ctx, req.(*RevokeCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_IsRevoked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsRevokedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).IsRevoked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_IsRevoked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).IsRevoked(ctx, req.(*IsRevokedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_RevocationSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevocationSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).RevocationSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registry_RevocationSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).RevocationSnapshot(ctx, req.(*RevocationSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Registry_ServiceDesc is the grpc.ServiceDesc for Registry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Registry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keel.cluster.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _Registry_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _Registry_Unsubscribe_Handler,
		},
		{
			MethodName: "NodesFor",
			Handler:    _Registry_NodesFor_Handler,
		},
		{
			MethodName: "ClaimSession",
			Handler:    _Registry_ClaimSession_Handler,
		},
		{
			MethodName: "ReleaseSession",
			Handler:    _Registry_ReleaseSession_Handler,
		},
		{
			MethodName: "EvaluateACL",
			Handler:    _Registry_EvaluateACL_Handler,
		},
		{
			MethodName: "ACLSnapshot",
			Handler:    _Registry_ACLSnapshot_Handler,
		},
		{
			MethodName: "CurrentRedisPrimary",
			Handler:    _Registry_CurrentRedisPrimary_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _Registry_CreateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _Registry_DeleteRole_Handler,
		},
		{
			MethodName: "CreateBinding",
			Handler:    _Registry_CreateBinding_Handler,
		},
		{
			MethodName: "DeleteBinding",
			Handler:    _Registry_DeleteBinding_Handler,
		},
		{
			MethodName: "EnableRuleset",
			Handler:    _Registry_EnableRuleset_Handler,
		},
		{
			MethodName: "DisableRuleset",
			Handler:    _Registry_DisableRuleset_Handler,
		},
		{
			MethodName: "RevokeCertificate",
			Handler:    _Registry_RevokeCertificate_Handler,
		},
		{
			MethodName: "IsRevoked",
			Handler:    _Registry_IsRevoked_Handler,
		},
		{
			MethodName: "RevocationSnapshot",
			Handler:    _Registry_RevocationSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/cluster/proto/cluster.proto",
}

const (
	Dataplane_Forward_FullMethodName = "/keel.cluster.Dataplane/Forward"
	Dataplane_Evict_FullMethodName   = "/keel.cluster.Dataplane/Evict"
)

// DataplaneClient is the client API for Dataplane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Dataplane carries MQTT message payloads directly between nodes,
// point-to-point, kept off the raft log entirely. This is the phase-1
// implementation of internal/cluster/dataplane.Forwarder; a future
// implementation may replace it with embedded NATS without changing the
// Forwarder interface.
type DataplaneClient interface {
	Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error)
	// Evict tells the receiving node to locally disconnect clientID — sent
	// by the node that just won a ClaimSession takeover, to the node that
	// previously owned the session (see internal/broker/hooks.go's
	// OnConnectAuthenticate). Best-effort: the caller does not block the
	// new connection on this succeeding: the evicted node's own MQTT
	// keepalive/TCP timeout is the backstop if this RPC is lost.
	Evict(ctx context.Context, in *EvictRequest, opts ...grpc.CallOption) (*EvictResponse, error)
}

type dataplaneClient struct {
	cc grpc.ClientConnInterface
}

func NewDataplaneClient(cc grpc.ClientConnInterface) DataplaneClient {
	return &dataplaneClient{cc}
}

func (c *dataplaneClient) Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardResponse)
	err := c.cc.Invoke(ctx, Dataplane_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneClient) Evict(ctx context.Context, in *EvictRequest, opts ...grpc.CallOption) (*EvictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvictResponse)
	err := c.cc.Invoke(ctx, Dataplane_Evict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataplaneServer is the server API for Dataplane service.
// All implementations must embed UnimplementedDataplaneServer
// for forward compatibility.
//
// Dataplane carries MQTT message payloads directly between nodes,
// point-to-point, kept off the raft log entirely. This is the phase-1
// implementation of internal/cluster/dataplane.Forwarder; a future
// implementation may replace it with embedded NATS without changing the
// Forwarder interface.
type DataplaneServer interface {
	Forward(context.Context, *ForwardRequest) (*ForwardResponse, error)
	// Evict tells the receiving node to locally disconnect clientID — sent
	// by the node that just won a ClaimSession takeover, to the node that
	// previously owned the session (see internal/broker/hooks.go's
	// OnConnectAuthenticate). Best-effort: the caller does not block the
	// new connection on this succeeding: the evicted node's own MQTT
	// keepalive/TCP timeout is the backstop if this RPC is lost.
	Evict(context.Context, *EvictRequest) (*EvictResponse, error)
	mustEmbedUnimplementedDataplaneServer()
}

// UnimplementedDataplaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataplaneServer struct{}

func (UnimplementedDataplaneServer) Forward(context.Context, *ForwardRequest) (*ForwardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedDataplaneServer) Evict(context.Context, *EvictRequest) (*EvictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evict not implemented")
}
func (UnimplementedDataplaneServer) mustEmbedUnimplementedDataplaneServer() {}
func (UnimplementedDataplaneServer) testEmbeddedByValue()                   {}

// UnsafeDataplaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataplaneServer will
// result in compilation errors.
type UnsafeDataplaneServer interface {
	mustEmbedUnimplementedDataplaneServer()
}

func RegisterDataplaneServer(s grpc.ServiceRegistrar, srv DataplaneServer) {
	// If the following call panics, it indicates UnimplementedDataplaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dataplane_ServiceDesc, srv)
}

func _Dataplane_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dataplane_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServer).Forward(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dataplane_Evict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServer).Evict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dataplane_Evict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServer).Evict(ctx, req.(*EvictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dataplane_ServiceDesc is the grpc.ServiceDesc for Dataplane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dataplane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keel.cluster.Dataplane",
	HandlerType: (*DataplaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forward",
			Handler:    _Dataplane_Forward_Handler,
		},
		{
			MethodName: "Evict",
			Handler:    _Dataplane_Evict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/cluster/proto/cluster.proto",
}
